# Generated by Django 5.0.3 on 2024-04-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scranotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note_tile',
            new_name='note_title',
        ),
    ]
