# Generated by Django 5.0.3 on 2024-03-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_type', models.CharField(blank=True, choices=[('LTO', 'LTO'), ('RISA', 'RISA'), ('FINWISE', 'FINWISE')], max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('open_state', models.CharField(blank=True, choices=[('Alabama', 'AL'), ('Alaska', 'AK'), ('Arizona', 'AZ'), ('Arkansas', 'AR'), ('California', 'CA'), ('Colorado', 'CO'), ('Connecticut', 'CT'), ('Delaware', 'DE'), ('Florida', 'FL'), ('Georgia', 'GA'), ('Hawái', 'HI'), ('Idaho', 'ID'), ('Illinois', 'IL'), ('Indiana', 'IN'), ('Iowa', 'IA'), ('Kansas', 'KS'), ('Kentucky', 'KY'), ('Luisiana', 'LA'), ('Maine', 'ME'), ('Maryland', 'MD'), ('Massachusetts', 'MA'), ('Míchigan', 'MI'), ('Minnesota', 'MN'), ('Misisipi', 'MS'), ('Misuri', 'MO'), ('Montana', 'MT'), ('Nebraska', 'NE'), ('Nevada', 'NV'), ('Nuevo Hampshire', 'NH'), ('Nueva Jersey', 'NJ'), ('Nuevo México', 'NM'), ('Nueva York', 'NY'), ('Carolina del Norte', 'NC'), ('Dakota del Norte', 'ND'), ('Ohio', 'OH'), ('Oklahoma', 'OK'), ('Oregón', 'OR'), ('Pensilvania', 'PA'), ('Rhode Island', 'RI'), ('Carolina del Sur', 'SC'), ('Dakota del Sur', 'SD'), ('Tennessee', 'TN'), ('Texas', 'TX'), ('Utah', 'UT'), ('Vermont', 'VT'), ('Virginia', 'VA'), ('Washington', 'WA'), ('Virginia Occidental', 'WV'), ('Wisconsin', 'WI'), ('Wyoming', 'WY')], max_length=50, null=True)),
                ('acc_status', models.CharField(choices=[('Charge-off', 'Charge-off'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=50)),
                ('date_request', models.DateField(blank=True, null=True)),
                ('method_notification', models.CharField(choices=[('Verbal', 'Verbal'), ('Writen', 'Wrinten'), ('Agency', 'Agency')], max_length=50)),
                ('date_open_acc', models.DateField(blank=True, null=True)),
                ('military_date', models.DateField(blank=True, null=True)),
                ('quealify', models.BooleanField()),
                ('status_notes', models.TextField(blank=True, null=True)),
                ('amount_refund', models.CharField(blank=True, max_length=50, null=True)),
                ('the_way_refund', models.CharField(blank=True, max_length=50, null=True)),
                ('date_refund', models.DateField(blank=True, null=True)),
                ('where_fees', models.CharField(blank=True, max_length=50, null=True)),
                ('where_waived', models.CharField(blank=True, max_length=50, null=True)),
                ('waive_interest', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
