# Generated by Django 5.0.3 on 2024-03-30 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_type', models.CharField(blank=True, choices=[('LTO', 'LTO'), ('RISA', 'RISA'), ('FINWISE', 'FINWISE')], max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('open_state', models.CharField(blank=True, choices=[('Alabama', 'AL'), ('Alaska', 'AK'), ('Arizona', 'AZ'), ('Arkansas', 'AR'), ('California', 'CA'), ('Colorado', 'CO'), ('Connecticut', 'CT'), ('Delaware', 'DE'), ('Florida', 'FL'), ('Georgia', 'GA'), ('Hawái', 'HI'), ('Idaho', 'ID'), ('Illinois', 'IL'), ('Indiana', 'IN'), ('Iowa', 'IA'), ('Kansas', 'KS'), ('Kentucky', 'KY'), ('Luisiana', 'LA'), ('Maine', 'ME'), ('Maryland', 'MD'), ('Massachusetts', 'MA'), ('Míchigan', 'MI'), ('Minnesota', 'MN'), ('Misisipi', 'MS'), ('Misuri', 'MO'), ('Montana', 'MT'), ('Nebraska', 'NE'), ('Nevada', 'NV'), ('Nuevo Hampshire', 'NH'), ('Nueva Jersey', 'NJ'), ('Nuevo México', 'NM'), ('Nueva York', 'NY'), ('Carolina del Norte', 'NC'), ('Dakota del Norte', 'ND'), ('Ohio', 'OH'), ('Oklahoma', 'OK'), ('Oregón', 'OR'), ('Pensilvania', 'PA'), ('Rhode Island', 'RI'), ('Carolina del Sur', 'SC'), ('Dakota del Sur', 'SD'), ('Tennessee', 'TN'), ('Texas', 'TX'), ('Utah', 'UT'), ('Vermont', 'VT'), ('Virginia', 'VA'), ('Washington', 'WA'), ('Virginia Occidental', 'WV'), ('Wisconsin', 'WI'), ('Wyoming', 'WY')], max_length=50, null=True)),
                ('acc_status', models.CharField(choices=[('Charge-off', 'Charge-off'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=50)),
                ('date_request', models.DateField(blank=True, null=True)),
                ('method_notification', models.CharField(choices=[('Verbal', 'Verbal'), ('Writen', 'Wrinten'), ('Agency', 'Agency')], max_length=50)),
                ('date_open_acc', models.DateField(blank=True, null=True)),
                ('military_date', models.DateField(blank=True, null=True)),
                ('qualify', models.BooleanField()),
                ('status_notes', models.TextField(blank=True, null=True)),
                ('date_mil', models.DateField(blank=True, null=True)),
                ('date_alert_dl', models.DateField(blank=True, null=True)),
                ('date_2mil', models.DateField(blank=True, null=True)),
                ('amount_refund', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('the_way_refund', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('date_refund', models.DateField(blank=True, default='N/A', null=True)),
                ('where_fees', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custumer_add', to=settings.AUTH_USER_MODEL)),
                ('first_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_review_candidates', to=settings.AUTH_USER_MODEL)),
                ('second_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_review_candidates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custumer_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('street2', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, choices=[('Alabama', 'AL'), ('Alaska', 'AK'), ('Arizona', 'AZ'), ('Arkansas', 'AR'), ('California', 'CA'), ('Colorado', 'CO'), ('Connecticut', 'CT'), ('Delaware', 'DE'), ('Florida', 'FL'), ('Georgia', 'GA'), ('Hawái', 'HI'), ('Idaho', 'ID'), ('Illinois', 'IL'), ('Indiana', 'IN'), ('Iowa', 'IA'), ('Kansas', 'KS'), ('Kentucky', 'KY'), ('Luisiana', 'LA'), ('Maine', 'ME'), ('Maryland', 'MD'), ('Massachusetts', 'MA'), ('Míchigan', 'MI'), ('Minnesota', 'MN'), ('Misisipi', 'MS'), ('Misuri', 'MO'), ('Montana', 'MT'), ('Nebraska', 'NE'), ('Nevada', 'NV'), ('Nuevo Hampshire', 'NH'), ('Nueva Jersey', 'NJ'), ('Nuevo México', 'NM'), ('Nueva York', 'NY'), ('Carolina del Norte', 'NC'), ('Dakota del Norte', 'ND'), ('Ohio', 'OH'), ('Oklahoma', 'OK'), ('Oregón', 'OR'), ('Pensilvania', 'PA'), ('Rhode Island', 'RI'), ('Carolina del Sur', 'SC'), ('Dakota del Sur', 'SD'), ('Tennessee', 'TN'), ('Texas', 'TX'), ('Utah', 'UT'), ('Vermont', 'VT'), ('Virginia', 'VA'), ('Washington', 'WA'), ('Virginia Occidental', 'WV'), ('Wisconsin', 'WI'), ('Wyoming', 'WY')], max_length=150, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=25, null=True)),
                ('return_type', models.CharField(blank=True, choices=[('MILR', 'MILR'), ('DLR', 'DLR'), ('ALR', 'ALR')], max_length=50, null=True)),
                ('return_note', models.TextField(blank=True, null=True)),
                ('address_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Return', 'Return')], max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_add', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_update', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to='tracker.customer')),
            ],
            options={
                'verbose_name': 'Customer Addresse',
            },
        ),
    ]
