# Generated by Django 5.0.3 on 2024-03-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='quealify',
            new_name='qualify',
        ),
    ]
