# Generated by Django 5.0.3 on 2024-03-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='waive_interest',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='where_waived',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
