# Generated by Django 5.0.3 on 2024-03-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount_refund',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_refund',
            field=models.DateField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='the_way_refund',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='waive_interest',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='where_fees',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='where_waived',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
