# Generated by Django 5.0.3 on 2024-04-01 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_customer_waive_interest_customer_where_waived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_2mil',
            new_name='danial_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='denial_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custumer_dl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='denial_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
