# Generated by Django 5.0.3 on 2024-04-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_date_2mil_customer_danial_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_refund',
            field=models.DateField(blank=True, null=True),
        ),
    ]
