# Generated by Django 5.0.3 on 2024-04-01 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_customer_date_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_refund',
        ),
    ]
