# Generated by Django 5.0.3 on 2024-04-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_customer_date_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_refund',
            field=models.DateField(blank=True, null=True),
        ),
    ]
