# Generated by Django 5.0.4 on 2024-04-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_rename_customer_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['created'], 'verbose_name': 'Customer Addresse'},
        ),
    ]
