# Generated by Django 5.0.4 on 2024-05-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_address_options_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicates',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='duplicates',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
