# Generated by Django 5.0.4 on 2024-05-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_account_pending_account_pending_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pending_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='resolve_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
