# Generated by Django 5.0.4 on 2024-06-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_account_pending_by_account_resolve_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
