# Generated by Django 5.0.4 on 2024-06-09 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_account_customer_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='open_state',
            field=models.CharField(blank=True, choices=[('Alabama', 'AL'), ('Alaska', 'AK'), ('Arizona', 'AZ'), ('Arkansas', 'AR'), ('California', 'CA'), ('Colorado', 'CO'), ('Connecticut', 'CT'), ('Delaware', 'DE'), ('Florida', 'FL'), ('Georgia', 'GA'), ('Hawái', 'HI'), ('Idaho', 'ID'), ('Illinois', 'IL'), ('Indiana', 'IN'), ('Iowa', 'IA'), ('Kansas', 'KS'), ('Kentucky', 'KY'), ('Luisiana', 'LA'), ('Maine', 'ME'), ('Maryland', 'MD'), ('Massachusetts', 'MA'), ('Míchigan', 'MI'), ('Minnesota', 'MN'), ('Misisipi', 'MS'), ('Misuri', 'MO'), ('Montana', 'MT'), ('Nebraska', 'NE'), ('Nevada', 'NV'), ('Nuevo Hampshire', 'NH'), ('Nueva Jersey', 'NJ'), ('Nuevo México', 'NM'), ('Nueva York', 'NY'), ('Carolina del Norte', 'NC'), ('Dakota del Norte', 'ND'), ('Ohio', 'OH'), ('Oklahoma', 'OK'), ('Oregón', 'OR'), ('Pennsylvania', 'PA'), ('Rhode Island', 'RI'), ('Carolina del Sur', 'SC'), ('Dakota del Sur', 'SD'), ('Tennessee', 'TN'), ('Texas', 'TX'), ('Utah', 'UT'), ('Vermont', 'VT'), ('Virginia', 'VA'), ('Washington', 'WA'), ('Virginia Occidental', 'WV'), ('Wisconsin', 'WI'), ('Wyoming', 'WY')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, choices=[('Alabama', 'AL'), ('Alaska', 'AK'), ('Arizona', 'AZ'), ('Arkansas', 'AR'), ('California', 'CA'), ('Colorado', 'CO'), ('Connecticut', 'CT'), ('Delaware', 'DE'), ('Florida', 'FL'), ('Georgia', 'GA'), ('Hawái', 'HI'), ('Idaho', 'ID'), ('Illinois', 'IL'), ('Indiana', 'IN'), ('Iowa', 'IA'), ('Kansas', 'KS'), ('Kentucky', 'KY'), ('Luisiana', 'LA'), ('Maine', 'ME'), ('Maryland', 'MD'), ('Massachusetts', 'MA'), ('Míchigan', 'MI'), ('Minnesota', 'MN'), ('Misisipi', 'MS'), ('Misuri', 'MO'), ('Montana', 'MT'), ('Nebraska', 'NE'), ('Nevada', 'NV'), ('Nuevo Hampshire', 'NH'), ('Nueva Jersey', 'NJ'), ('Nuevo México', 'NM'), ('Nueva York', 'NY'), ('Carolina del Norte', 'NC'), ('Dakota del Norte', 'ND'), ('Ohio', 'OH'), ('Oklahoma', 'OK'), ('Oregón', 'OR'), ('Pennsylvania', 'PA'), ('Rhode Island', 'RI'), ('Carolina del Sur', 'SC'), ('Dakota del Sur', 'SD'), ('Tennessee', 'TN'), ('Texas', 'TX'), ('Utah', 'UT'), ('Vermont', 'VT'), ('Virginia', 'VA'), ('Washington', 'WA'), ('Virginia Occidental', 'WV'), ('Wisconsin', 'WI'), ('Wyoming', 'WY')], max_length=150, null=True),
        ),
    ]
