# Generated by Django 5.0.4 on 2024-06-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_account_approved_by_alter_account_open_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
