# Generated by Django 5.0.4 on 2024-06-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_account_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='qualify',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
