# Generated by Django 5.0.4 on 2024-06-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_alter_account_qualify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
