# Generated by Django 5.0.4 on 2024-06-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_alter_account_qualify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='qualify',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
