# Generated by Django 5.0.4 on 2024-04-12 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0008_customer_info_alter_address_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_notification', models.CharField(choices=[('Customer', 'Customer'), ('RPA', 'RPA')], max_length=50)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('email_received', models.TextField()),
                ('email_sent', models.TextField(blank=True, null=True)),
                ('valid', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_add', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
