# Generated by Django 5.0.4 on 2024-04-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scra_inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
