# Generated by Django 5.0.4 on 2024-04-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scra_inbox', '0002_alter_inbox_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
