# Generated by Django 5.0.4 on 2024-04-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scra_inbox', '0004_inbox_email_sent_date_inbox_sent_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='sent_by',
        ),
    ]
